FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

EXPOSE 8000

CMD ["npx", "expo", "start", "--web", "--host", "lan", "--port", "8000"]