# Generated by Django 5.1.3 on 2025-10-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
