# Generated by Django 5.1.3 on 2025-10-20 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_alter_user_subscription_start'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
        migrations.AlterModelTable(
            name='user_profile',
            table='User_Profile',
        ),
    ]
