# Generated by Django 5.1.3 on 2025-10-22 00:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_alter_profile_table_alter_user_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learning_Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('articulation', 'Articulation'), ('language_building', 'Language Building'), ('comprehension', 'Comprehension')], max_length=20)),
                ('image', models.URLField(blank=True, null=True)),
                ('num_tasks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Learning_Unit',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participation_type', models.CharField(choices=[('required', 'Required'), ('recommended', 'Recommended')], max_length=15)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('num_tasks_completed', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_assignments', to='controller.user')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='controller.profile')),
                ('learning_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='controller.learning_unit')),
            ],
            options={
                'db_table': 'Assignment',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='controller.learning_unit')),
            ],
            options={
                'db_table': 'Task',
            },
        ),
        migrations.CreateModel(
            name='Task_Progress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_start_time', models.DateTimeField(auto_now_add=True)),
                ('session_end_time', models.DateTimeField(blank=True, null=True)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('attempts_made', models.IntegerField(default=0)),
                ('got_correct', models.BooleanField(default=False)),
                ('accuracy', models.FloatField(default=0.0)),
                ('answer_data', models.JSONField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progresses', to='controller.assignment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progresses', to='controller.task')),
            ],
            options={
                'db_table': 'Task_Progress',
            },
        ),
    ]
