# Generated by Django 5.1.3 on 2025-10-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_learning_unit_assignment_task_task_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='question_data',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='task',
            name='speaking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('match', 'Match'), ('question', 'Question'), ('true_false', 'True False')], default=None, max_length=20),
        ),
    ]
