# Generated by Django 5.1.3 on 2025-10-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_task_question_data_task_speaking_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='child_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('match', 'Match'), ('question', 'Question'), ('true_false', 'True False'), ('re-order', 'Re-order'), ('conversation', 'Conversation')], default=None, max_length=20),
        ),
    ]
