# Generated by Django 5.1.3 on 2025-10-29 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_profile_child_details_alter_task_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_progress',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task_progress',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='num_tasks_completed',
        ),
        migrations.RemoveField(
            model_name='learning_unit',
            name='num_tasks',
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='controller.learning_unit')),
            ],
            options={
                'db_table': 'Exercise',
            },
        ),
        migrations.CreateModel(
            name='Exercise_Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_spent', models.IntegerField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_results', to='controller.assignment')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_results', to='controller.exercise')),
            ],
            options={
                'db_table': 'Exercise_Result',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Task_Progress',
        ),
    ]
