# Generated by Django 5.1.3 on 2025-10-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0008_question'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='Question',
        ),
    ]
