# Generated by Django 5.1.3 on 2025-10-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0009_alter_question_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('multiple_drag', 'Multiple Drag'), ('multiple_select', 'Multiple Select'), ('ordered_drag', 'Ordered Drag'), ('speaking', 'Speaking')], default='multiple_drag', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_drag', 'Multiple Drag'), ('multiple_select', 'Multiple Select'), ('ordered_drag', 'Ordered Drag'), ('speaking', 'Speaking')], max_length=20),
        ),
    ]
