# Generated by Django 5.1.3 on 2025-10-29 23:55

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0010_exercise_exercise_type_alter_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child_Embedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='controller.profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_embeddings', to='controller.question')),
            ],
            options={
                'db_table': 'Child_Embedding',
            },
        ),
        migrations.CreateModel(
            name='Question_Embedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_embeddings', to='controller.question')),
            ],
            options={
                'db_table': 'Question_Embedding',
            },
        ),
    ]
