# Generated by Django 5.1.3 on 2025-10-30 11:52

import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0011_child_embedding_question_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rag_Context',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.TextField()),
                ('source_url', models.TextField()),
                ('content_chunk', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Rag_Context',
            },
        ),
    ]
