# Generated by Django 5.1.3 on 2025-11-02 07:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0012_rag_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='child_embedding',
            name='child_input_text',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise_result',
            name='num_correct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise_result',
            name='num_incorrect',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question_embedding',
            name='expected_answer_text',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Question_Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_attempts', models.IntegerField(blank=True, null=True)),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('exercise_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='controller.exercise_result')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='controller.question')),
            ],
            options={
                'db_table': 'Question_Result',
            },
        ),
    ]
