# Generated by Django 5.1.3 on 2025-11-13 04:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0016_alter_exercise_result_accuracy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascot_Items',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('head', 'Head'), ('torso', 'Torso')], max_length=10)),
                ('icon_image', models.URLField()),
                ('mascot_image', models.JSONField()),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Mascot_Item',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipped', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='controller.profile')),
                ('mascot_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='controller.mascot_items')),
            ],
            options={
                'db_table': 'Inventory',
            },
        ),
    ]
