# Generated by Django 5.1.3 on 2025-11-13 22:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0017_mascot_items_profile_coins_profile_streak_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_chat_rooms', to='controller.profile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_chat_rooms', to='controller.profile')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_chat_rooms', to='controller.profile')),
            ],
            options={
                'db_table': 'Chat_Room',
            },
        ),
        migrations.CreateModel(
            name='Chat_Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='controller.profile')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='controller.chat_room')),
            ],
            options={
                'db_table': 'Chat_Message',
            },
        ),
    ]
