# Generated by Django 5.1.3 on 2025-11-15 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0018_chat_room_chat_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_room',
            old_name='parent',
            new_name='messenger_1',
        ),
        migrations.RenameField(
            model_name='chat_room',
            old_name='therapist',
            new_name='messenger_2',
        ),
    ]