# Generated by Django 5.1.3 on 2025-11-17 07:19

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0019_rename_chat_room_fields'),
    ]

    operations = [
        VectorExtension(),
    ]
